---
coolify_enabled: false
coolify_base_dir: /data/coolify
coolify_source_dir: "{{ coolify_base_dir }}/source"
coolify_app_url: ""
coolify_app_port: "8000"
coolify_proxy_ui_enabled: false
coolify_proxy_hostname: ""
coolify_admin_create_enabled: false
coolify_admin_name: ""
coolify_admin_email: ""
coolify_admin_password: ""
coolify_default_project_enabled: false
coolify_default_project_name: "Default"
coolify_cdn_base_url: https://cdn.coollabs.io/coolify
coolify_compose_files:
  - docker-compose.yml
  - docker-compose.prod.yml
coolify_required_directories:
  - "{{ coolify_base_dir }}/source"
  - "{{ coolify_base_dir }}/ssh/keys"
  - "{{ coolify_base_dir }}/ssh/mux"
  - "{{ coolify_base_dir }}/applications"
  - "{{ coolify_base_dir }}/databases"
  - "{{ coolify_base_dir }}/backups"
  - "{{ coolify_base_dir }}/services"
  - "{{ coolify_base_dir }}/proxy/dynamic"
  - "{{ coolify_base_dir }}/webhooks-during-maintenance"
