---
forgejo_runner_enabled: false
forgejo_runner_registered: false
forgejo_runner_app_dir: /opt/forgejo-runner
forgejo_runner_data_dir: /opt/forgejo-runner/data
forgejo_runner_image: data.forgejo.org/forgejo/runner:4.0.0
forgejo_runner_dind_image: docker:28-dind
forgejo_runner_name: codeberg-runner
forgejo_runner_labels:
  - "docker:docker://node:22-bookworm"
forgejo_runner_capacity: 1

