---
- name: Create Forgejo runner directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  loop:
    - "{{ forgejo_runner_app_dir }}"
    - "{{ forgejo_runner_data_dir }}"

- name: Install Forgejo runner compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ forgejo_runner_app_dir }}/compose.yml"
    owner: root
    group: root
    mode: "0640"
  notify: restart forgejo runner

- name: Start Forgejo runner stack
  ansible.builtin.command: "docker compose -f {{ forgejo_runner_app_dir }}/compose.yml up -d"
  changed_when: true

