version: 1

project:
    name: blog-domi-ninja
    environment: prod

build:
    context: .
    dockerfile: Dockerfile
    tags:
        - "localhost/blog-domi-ninja:${git_sha}"

hosts:
    p3:
        ssh: root@p3.domi.ninja
        roles: [web]

services:
    web:
        image: "localhost/blog-domi-ninja:${git_sha}"
        hosts: [p3]
        ports:
            - host_ip: 127.0.0.1
              published: auto
              target: 80
        health:
            command: ["wget", "-q", "--spider", "http://127.0.0.1/"]
            timeout_seconds: 60

routes:
    - host: blog.domi.ninja
      service: web
